n = (input('Digite algo:'))
print(type(n))
print('É alfanumérico?', n.isalnum())
print('É alfabético?', n.isalpha())
print('É número?', n.isnumeric())
print('É maiúscula?', n.isupper())
print('É minúscula?', n.islower())
print('É capitalizada?', n.istitle())
